### ISSUE TITLE
TypeError: "NetworkError when attempting to fetch resource."

### ISSUE THREAD

**Issue by Suzakura** [ukyoda/ogpParser#15]
OGP情報を取得してオリジナルのブログカードを作成しようと考えています。

環境はWordPress。
WordPressのエディタ（Gutenberg）はJavaScriptで構築されているようで、オリジナルブロックの作成にもJavaScriptを使用しています。

OGP情報をこのパーサーを使用して取得しようと考えていたのですが、外部リンクの情報を取得する時にタイトルのようなエラーが発生してしまいました。
（内部リンクは問題なく情報取得しています）

「CORS ヘッダー ‘Access-Control-Allow-Origin’ が足りない」とのことで、異なるドメインのURLから情報を参照する際に発生する様子。「同一生成元ポリシー」によるエラーのようですが、なんとかして外部リンク先のOGP情報を取得できないものでしょうか？

**Comment by ukyoda** [comment]
確認が遅くなりました。

このライブラリはサーバサイドの処理で利用する前提のライブラリとなります。
おそらくですが、WebpackやBabelなどでビルドして、フロントエンドの処理でこのライブラリを利用していませんでしょうか？

その場合、アクセス権はアクセス先のサーバが許可しているものをのぞいてこのライブラリは利用できません。

例えば、Wordpressと同一サーバにこのライブラリの結果を返却するようなラッパーAPIを作成して利用するのはいかがでしょうか？

**Comment by ukyoda** [comment]
本件CLOSEさせていただきます。

**Comment by taka1156** [comment]
glitchでExpressを利用したNode.jsサーバーを立てたのですがCORSで使えませんでした
