### ISSUE TITLE
ogp[], seo[], must be array?

### ISSUE THREAD

**Issue by nemu626** [ukyoda/ogpParser#3]
return値であるogp,seoは配列ではないほうがいいと思うのですがいかがですか？
returnされた配列内に内容が入っている場合でも、lengthが0なので処理するときに空行列として扱われる場合が多いです。

配列のlengthが正常な値になるように修正するか、オブジェクト型にした方が良いのではないでしょうか？

**Comment by ukyoda** [comment]
コメントありがとうございます。
確かに、return値のogp、seoは配列である必要はないですね;;
上記、対応版を v0.3.1 としてリリースいたしましたのでご確認をお願い致します。

**Comment by ukyoda** [comment]
上記、対応しているのでClose致します。
