### ISSUE TITLE
依存関係としてのaxiosを削除することはできますか？

### ISSUE THREAD

**Issue by SaadBazaz** [ukyoda/ogpParser#69]
こんにちは、
素晴らしいリポジトリに感謝します。不要な依存関係を避ける方法はありますか？私のプロジェクトではaxiosを一切使用しておらず、このライブラリにaxiosが必要な場合には大きな問題です。

**Comment by ukyoda** [comment]
ご連絡を頂きありがとうございます！

現在の実装ではaxiosが必須になっていますが、Node.jsの標準ライブラリを使ってHTTPリクエストするように改造すれば、依存を解消するように修正することは可能だと思います。

時間があるときに対応を検討してみたいと思います。

**Comment by ukyoda** [comment]
Hello!

I fixed to remove axios and released a new version v0.8.0.
You can install it from npm 👍🏼 
https://www.npmjs.com/package/ogp-parser

※ I'm sorry, I forgot to remove axios from package.json so I did and release v0.8.1. Please use v0.8.1 mm

**Comment by ukyoda** [comment]
I'd close this issue because I've already solved.

If it still unsolved, please reopen.

**Comment by SaadBazaz** [comment]
Thanks @ukyoda 
I used another package for now but I'll keep my eyes open for this.
